services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul-server
    ports:
      - "8500:8500"       
      - "8600:8600/udp"   
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    volumes:
      - ./consul/data:/consul/data
      - ./consul/config:/consul/config
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-service:
    build: ./config-service  
    container_name: config-service
    ports:
      - "8888:8888"            
    networks:
      - shared-network
    depends_on:
      consul:
        condition: service_healthy              
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONSUL_HOST: consul-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  student-service:
    build: ./student-service  
    container_name: student-service
    ports:
      - "8081:8081"  
    networks:
      - shared-network
    depends_on:
      consul:
        condition: service_healthy
      config-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONSUL_HOST: consul-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  classroom-service:
    build: ./classroom-service
    container_name: classroom-service
    ports:
      - "8082:8082"
    networks:
      - shared-network
    depends_on:
      consul:
        condition: service_healthy
      config-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONSUL_HOST: consul-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  subject-service:
    build: ./subject-service
    container_name: subject-service
    ports:
      - "8083:8083"
    networks:
      - shared-network
    depends_on:
      consul:
        condition: service_healthy
      config-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONSUL_HOST: consul-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "9999:9999"
    networks:
      - shared-network
    depends_on:
      consul:
        condition: service_healthy
      config-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONSUL_HOST: consul-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: passer
      MYSQL_DATABASE: school_management
      MYSQL_USER: user
      MYSQL_PASSWORD: passer
    ports:
      - "3306:3306"
    networks:
      - shared-network
    volumes:
      - mysql-data:/var/lib/mysql

  teacher-service:
    build: ./teacher-service
    container_name: teacher-service
    ports:
      - "3000:3000"
    networks:
      - shared-network
    depends_on:
      - consul
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: passer
      DB_NAME: school_management
      SPRING_PROFILES_ACTIVE: docker
      CONSUL_HOST: consul-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/teachers" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "5173:80"
    networks:
      - shared-network
    depends_on:
      consul:
        condition: service_healthy

networks:
  shared-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local